// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@3sixty/data-core";
import * as external0 from "@3sixty/data-json-ld";
import * as external1 from "../models/auditableItemStreamModes.js";
import * as external2 from "@3sixty/immutable-proof-models";
const MESSAGES = [
	"must be equal to constant",
	"must be object",
	"must NOT have fewer than 3 items",
	"must be array",
	"must be number",
	"must be boolean",
	"must NOT have fewer than 2 items",
	"must be string",
	"must NOT have more than 2 items"
];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the AuditableItemStream schema.
 */
export const CompiledAuditableItemStream: ICompiledValidator = validate52;
const keyword0 = external0["CompiledJsonLdContextDefinitionElement"];
const keyword1 = external0["CompiledJsonLdNodeObject"];

function validate54(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamEntryBase" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate54.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.type === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.entryObject === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "entryObject" },
				"must have required property '" + "entryObject" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.type !== undefined) {
			if ("AuditableItemStreamEntry" !== data.type) {
				const err2 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemStreamEntry" },
					0
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
		}
		if (data.entryObject !== undefined) {
			if (
				!keyword1(data.entryObject, {
					instancePath: instancePath + "/entryObject",
					parentData: data,
					parentDataProperty: "entryObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
				errors = vErrors.length;
			}
		}
	} else {
		const err3 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err3);
		errors++;
	}
	validate54.errors = vErrors;
	return errors === 0;
}
validate54.evaluated = {
	props: { type: true, entryObject: true },
	dynamicProps: false,
	dynamicItems: false
};

const keyword3 = Object.values(external1["AuditableItemStreamModes"]);

function validate56(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamModes" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate56.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (!keyword3.includes(data)) {
		for (let i0 = 0; i0 < keyword3.length; i0++) {
			vErrors = pushError(
				vErrors,
				createError(
					instancePath,
					"#/anyOf" + "/" + i0 + "/const",
					"const",
					{ allowedValue: keyword3[i0] },
					"must be equal to constant"
				)
			);
			errors++;
		}
		vErrors = pushError(
			vErrors,
			createError(instancePath, "#/anyOf", "anyOf", {}, "must match a schema in anyOf")
		);
		errors++;
	}
	validate56.errors = vErrors;
	return errors === 0;
}
validate56.evaluated = { dynamicProps: false, dynamicItems: false };

function validate53(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamBase" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate53.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 3) {
					const err2 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 3 },
						2
					);
					vErrors = pushError(vErrors, err2);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err3 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							0
						);
						vErrors = pushError(vErrors, err3);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/ais/" !== data0[1]) {
						const err4 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/ais/" },
							0
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 2) {
					if ("https://schema.3sixty.global/common/" !== data0[2]) {
						const err5 = createError(
							instancePath + "/@context/2",
							"#/properties/%40context/prefixItems/2/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							0
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 3;
				if (!valid2) {
					for (let i0 = 3; i0 < len1; i0++) {
						const _errs6 = errors;
						if (
							!keyword0(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs6 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemStream" !== data.type) {
				const err7 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemStream" },
					0
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.annotationObject !== undefined) {
			if (
				!keyword1(data.annotationObject, {
					instancePath: instancePath + "/annotationObject",
					parentData: data,
					parentDataProperty: "annotationObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
				errors = vErrors.length;
			}
		}
		if (data.entries !== undefined) {
			let data7 = data.entries;
			if (data7 && typeof data7 == "object" && !Array.isArray(data7)) {
				if (data7.type === undefined) {
					const err8 = createError(
						instancePath + "/entries",
						"#/properties/entries/required",
						"required",
						{ missingProperty: "type" },
						"must have required property '" + "type" + "'"
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				if (data7.itemListElement === undefined) {
					const err9 = createError(
						instancePath + "/entries",
						"#/properties/entries/required",
						"required",
						{ missingProperty: "itemListElement" },
						"must have required property '" + "itemListElement" + "'"
					);
					vErrors = pushError(vErrors, err9);
					errors++;
				}
				if (data7.type !== undefined) {
					if ("ItemList" !== data7.type) {
						const err10 = createError(
							instancePath + "/entries/type",
							"#/properties/entries/properties/type/const",
							"const",
							{ allowedValue: "ItemList" },
							0
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				if (data7.itemListElement !== undefined) {
					let data9 = data7.itemListElement;
					if (Array.isArray(data9)) {
						const len2 = data9.length;
						for (let i1 = 0; i1 < len2; i1++) {
							if (
								!validate54(data9[i1], {
									instancePath: instancePath + "/entries/itemListElement/" + i1,
									parentData: data9,
									parentDataProperty: i1,
									rootData,
									dynamicAnchors
								})
							) {
								vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
								errors = vErrors.length;
							}
						}
					} else {
						const err11 = createError(
							instancePath + "/entries/itemListElement",
							"#/properties/entries/properties/itemListElement/type",
							"type",
							{ type: "array" },
							3
						);
						vErrors = pushError(vErrors, err11);
						errors++;
					}
				}
			} else {
				const err12 = createError(
					instancePath + "/entries",
					"#/properties/entries/type",
					"type",
					{ type: "object" },
					1
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.immutableInterval !== undefined) {
			let data11 = data.immutableInterval;
			if (!(typeof data11 == "number" && isFinite(data11))) {
				const err13 = createError(
					instancePath + "/immutableInterval",
					"#/properties/immutableInterval/type",
					"type",
					{ type: "number" },
					4
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.closed !== undefined) {
			if (typeof data.closed !== "boolean") {
				const err14 = createError(
					instancePath + "/closed",
					"#/properties/closed/type",
					"type",
					{ type: "boolean" },
					5
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
		if (data.mode !== undefined) {
			if (
				!validate56(data.mode, {
					instancePath: instancePath + "/mode",
					parentData: data,
					parentDataProperty: "mode",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate56.errors : vErrors.concat(validate56.errors);
				errors = vErrors.length;
			}
		}
	} else {
		const err15 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err15);
		errors++;
	}
	validate53.errors = vErrors;
	return errors === 0;
}
validate53.evaluated = {
	props: {
		"@context": true,
		type: true,
		annotationObject: true,
		entries: true,
		immutableInterval: true,
		closed: true,
		mode: true
	},
	dynamicProps: false,
	dynamicItems: false
};

const keyword5 = external2["CompiledImmutableProofVerification"];

function validate59(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamEntry" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate59.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (
		!validate54(data, { instancePath, parentData, parentDataProperty, rootData, dynamicAnchors })
	) {
		vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
		errors = vErrors.length;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.id === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.dateCreated === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "dateCreated" },
				"must have required property '" + "dateCreated" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.index === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "index" },
				"must have required property '" + "index" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 2) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						6
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/ais/" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/ais/" },
							0
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/common/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							0
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid3 = len1 <= 2;
				if (!valid3) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs6 = errors;
						if (
							!keyword0(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
							errors = vErrors.length;
						}
						var valid3 = _errs6 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err7 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err8 = createError(
					instancePath + "/dateCreated",
					"#/properties/dateCreated/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.dateModified !== undefined) {
			if (typeof data.dateModified !== "string") {
				const err9 = createError(
					instancePath + "/dateModified",
					"#/properties/dateModified/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.dateDeleted !== undefined) {
			if (typeof data.dateDeleted !== "string") {
				const err10 = createError(
					instancePath + "/dateDeleted",
					"#/properties/dateDeleted/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
		if (data.userIdentity !== undefined) {
			if (typeof data.userIdentity !== "string") {
				const err11 = createError(
					instancePath + "/userIdentity",
					"#/properties/userIdentity/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
		}
		if (data.index !== undefined) {
			let data9 = data.index;
			if (!(typeof data9 == "number" && isFinite(data9))) {
				const err12 = createError(
					instancePath + "/index",
					"#/properties/index/type",
					"type",
					{ type: "number" },
					4
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.proofId !== undefined) {
			if (typeof data.proofId !== "string") {
				const err13 = createError(
					instancePath + "/proofId",
					"#/properties/proofId/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.verification !== undefined) {
			if (
				!keyword5(data.verification, {
					instancePath: instancePath + "/verification",
					parentData: data,
					parentDataProperty: "verification",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword5.errors : vErrors.concat(keyword5.errors);
				errors = vErrors.length;
			}
		}
	} else {
		const err14 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err14);
		errors++;
	}
	validate59.errors = vErrors;
	return errors === 0;
}
validate59.evaluated = {
	props: {
		"@context": true,
		id: true,
		dateCreated: true,
		dateModified: true,
		dateDeleted: true,
		userIdentity: true,
		index: true,
		proofId: true,
		verification: true,
		type: true,
		entryObject: true
	},
	dynamicProps: false,
	dynamicItems: false
};

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStream" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (
		!validate53(data, { instancePath, parentData, parentDataProperty, rootData, dynamicAnchors })
	) {
		vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
		errors = vErrors.length;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.id === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.dateCreated === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "dateCreated" },
				"must have required property '" + "dateCreated" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err2 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
		}
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err3 = createError(
					instancePath + "/dateCreated",
					"#/properties/dateCreated/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
		}
		if (data.dateModified !== undefined) {
			if (typeof data.dateModified !== "string") {
				const err4 = createError(
					instancePath + "/dateModified",
					"#/properties/dateModified/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err4);
				errors++;
			}
		}
		if (data.organizationIdentity !== undefined) {
			if (typeof data.organizationIdentity !== "string") {
				const err5 = createError(
					instancePath + "/organizationIdentity",
					"#/properties/organizationIdentity/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err5);
				errors++;
			}
		}
		if (data.userIdentity !== undefined) {
			if (typeof data.userIdentity !== "string") {
				const err6 = createError(
					instancePath + "/userIdentity",
					"#/properties/userIdentity/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.proofId !== undefined) {
			if (typeof data.proofId !== "string") {
				const err7 = createError(
					instancePath + "/proofId",
					"#/properties/proofId/type",
					"type",
					{ type: "string" },
					7
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.numberOfItems !== undefined) {
			let data6 = data.numberOfItems;
			if (!(typeof data6 == "number" && isFinite(data6))) {
				const err8 = createError(
					instancePath + "/numberOfItems",
					"#/properties/numberOfItems/type",
					"type",
					{ type: "number" },
					4
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.entries !== undefined) {
			let data7 = data.entries;
			if (data7 && typeof data7 == "object" && !Array.isArray(data7)) {
				if (data7.type === undefined) {
					const err9 = createError(
						instancePath + "/entries",
						"#/properties/entries/required",
						"required",
						{ missingProperty: "type" },
						"must have required property '" + "type" + "'"
					);
					vErrors = pushError(vErrors, err9);
					errors++;
				}
				if (data7.itemListElement === undefined) {
					const err10 = createError(
						instancePath + "/entries",
						"#/properties/entries/required",
						"required",
						{ missingProperty: "itemListElement" },
						"must have required property '" + "itemListElement" + "'"
					);
					vErrors = pushError(vErrors, err10);
					errors++;
				}
				if (data7.type !== undefined) {
					if ("ItemList" !== data7.type) {
						const err11 = createError(
							instancePath + "/entries/type",
							"#/properties/entries/properties/type/const",
							"const",
							{ allowedValue: "ItemList" },
							0
						);
						vErrors = pushError(vErrors, err11);
						errors++;
					}
				}
				if (data7.itemListElement !== undefined) {
					let data9 = data7.itemListElement;
					if (Array.isArray(data9)) {
						const len0 = data9.length;
						for (let i0 = 0; i0 < len0; i0++) {
							if (
								!validate59(data9[i0], {
									instancePath: instancePath + "/entries/itemListElement/" + i0,
									parentData: data9,
									parentDataProperty: i0,
									rootData,
									dynamicAnchors
								})
							) {
								vErrors = vErrors === null ? validate59.errors : vErrors.concat(validate59.errors);
								errors = vErrors.length;
							}
						}
					} else {
						const err12 = createError(
							instancePath + "/entries/itemListElement",
							"#/properties/entries/properties/itemListElement/type",
							"type",
							{ type: "array" },
							3
						);
						vErrors = pushError(vErrors, err12);
						errors++;
					}
				}
			} else {
				const err13 = createError(
					instancePath + "/entries",
					"#/properties/entries/type",
					"type",
					{ type: "object" },
					1
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.verification !== undefined) {
			if (
				!keyword5(data.verification, {
					instancePath: instancePath + "/verification",
					parentData: data,
					parentDataProperty: "verification",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword5.errors : vErrors.concat(keyword5.errors);
				errors = vErrors.length;
			}
		}
	} else {
		const err14 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err14);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = {
	props: {
		id: true,
		dateCreated: true,
		dateModified: true,
		organizationIdentity: true,
		userIdentity: true,
		proofId: true,
		numberOfItems: true,
		entries: true,
		verification: true,
		"@context": true,
		type: true,
		annotationObject: true,
		immutableInterval: true,
		closed: true,
		mode: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemStreamBase schema.
 */
export const CompiledAuditableItemStreamBase: ICompiledValidator = validate53;

/**
 * Compiled validator for the AuditableItemStreamModes schema.
 */
export const CompiledAuditableItemStreamModes: ICompiledValidator = validate56;

/**
 * Compiled validator for the AuditableItemStreamList schema.
 */
export const CompiledAuditableItemStreamList: ICompiledValidator = validate62;

function validate62(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamList" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate62.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.itemListElement === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "itemListElement" },
				"must have required property '" + "itemListElement" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 3) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 3 },
						2
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							0
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/ais/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/ais/" },
							0
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				if (len0 > 2) {
					if ("https://schema.3sixty.global/common/" !== data0[2]) {
						const err6 = createError(
							instancePath + "/@context/2",
							"#/properties/%40context/prefixItems/2/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							0
						);
						vErrors = pushError(vErrors, err6);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 3;
				if (!valid2) {
					for (let i0 = 3; i0 < len1; i0++) {
						const _errs6 = errors;
						if (
							!keyword0(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs6 === errors;
					}
				}
			} else {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.type !== undefined) {
			let data5 = data.type;
			if (Array.isArray(data5)) {
				if (data5.length > 2) {
					const err8 = createError(
						instancePath + "/type",
						"#/properties/type/maxItems",
						"maxItems",
						{ limit: 2 },
						8
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				if (data5.length < 2) {
					const err9 = createError(
						instancePath + "/type",
						"#/properties/type/minItems",
						"minItems",
						{ limit: 2 },
						6
					);
					vErrors = pushError(vErrors, err9);
					errors++;
				}
				const len2 = data5.length;
				if (len2 > 0) {
					if ("ItemList" !== data5[0]) {
						const err10 = createError(
							instancePath + "/type/0",
							"#/properties/type/prefixItems/0/const",
							"const",
							{ allowedValue: "ItemList" },
							0
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("AuditableItemStreamList" !== data5[1]) {
						const err11 = createError(
							instancePath + "/type/1",
							"#/properties/type/prefixItems/1/const",
							"const",
							{ allowedValue: "AuditableItemStreamList" },
							0
						);
						vErrors = pushError(vErrors, err11);
						errors++;
					}
				}
				const len3 = data5.length;
				if (!(len3 <= 2)) {
					const err12 = createError(
						instancePath + "/type",
						"#/properties/type/items",
						"items",
						{ limit: 2 },
						8
					);
					vErrors = pushError(vErrors, err12);
					errors++;
				}
			} else {
				const err13 = createError(
					instancePath + "/type",
					"#/properties/type/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.itemListElement !== undefined) {
			let data8 = data.itemListElement;
			if (Array.isArray(data8)) {
				const len4 = data8.length;
				for (let i1 = 0; i1 < len4; i1++) {
					if (
						!validate52(data8[i1], {
							instancePath: instancePath + "/itemListElement/" + i1,
							parentData: data8,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err14 = createError(
					instancePath + "/itemListElement",
					"#/properties/itemListElement/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
	} else {
		const err15 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err15);
		errors++;
	}
	validate62.errors = vErrors;
	return errors === 0;
}
validate62.evaluated = {
	props: { "@context": true, type: true, itemListElement: true },
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemStreamEntry schema.
 */
export const CompiledAuditableItemStreamEntry: ICompiledValidator = validate59;

/**
 * Compiled validator for the AuditableItemStreamEntryBase schema.
 */
export const CompiledAuditableItemStreamEntryBase: ICompiledValidator = validate54;

/**
 * Compiled validator for the AuditableItemStreamEntryList schema.
 */
export const CompiledAuditableItemStreamEntryList: ICompiledValidator = validate64;

function validate64(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamEntryList" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate64.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.itemListElement === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "itemListElement" },
				"must have required property '" + "itemListElement" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 3) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 3 },
						2
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							0
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/ais/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/ais/" },
							0
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				if (len0 > 2) {
					if ("https://schema.3sixty.global/common/" !== data0[2]) {
						const err6 = createError(
							instancePath + "/@context/2",
							"#/properties/%40context/prefixItems/2/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							0
						);
						vErrors = pushError(vErrors, err6);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 3;
				if (!valid2) {
					for (let i0 = 3; i0 < len1; i0++) {
						const _errs6 = errors;
						if (
							!keyword0(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs6 === errors;
					}
				}
			} else {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.type !== undefined) {
			let data5 = data.type;
			if (Array.isArray(data5)) {
				if (data5.length > 2) {
					const err8 = createError(
						instancePath + "/type",
						"#/properties/type/maxItems",
						"maxItems",
						{ limit: 2 },
						8
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				if (data5.length < 2) {
					const err9 = createError(
						instancePath + "/type",
						"#/properties/type/minItems",
						"minItems",
						{ limit: 2 },
						6
					);
					vErrors = pushError(vErrors, err9);
					errors++;
				}
				const len2 = data5.length;
				if (len2 > 0) {
					if ("ItemList" !== data5[0]) {
						const err10 = createError(
							instancePath + "/type/0",
							"#/properties/type/prefixItems/0/const",
							"const",
							{ allowedValue: "ItemList" },
							0
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("AuditableItemStreamEntryList" !== data5[1]) {
						const err11 = createError(
							instancePath + "/type/1",
							"#/properties/type/prefixItems/1/const",
							"const",
							{ allowedValue: "AuditableItemStreamEntryList" },
							0
						);
						vErrors = pushError(vErrors, err11);
						errors++;
					}
				}
				const len3 = data5.length;
				if (!(len3 <= 2)) {
					const err12 = createError(
						instancePath + "/type",
						"#/properties/type/items",
						"items",
						{ limit: 2 },
						8
					);
					vErrors = pushError(vErrors, err12);
					errors++;
				}
			} else {
				const err13 = createError(
					instancePath + "/type",
					"#/properties/type/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.itemListElement !== undefined) {
			let data8 = data.itemListElement;
			if (Array.isArray(data8)) {
				const len4 = data8.length;
				for (let i1 = 0; i1 < len4; i1++) {
					if (
						!validate59(data8[i1], {
							instancePath: instancePath + "/itemListElement/" + i1,
							parentData: data8,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate59.errors : vErrors.concat(validate59.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err14 = createError(
					instancePath + "/itemListElement",
					"#/properties/itemListElement/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
	} else {
		const err15 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err15);
		errors++;
	}
	validate64.errors = vErrors;
	return errors === 0;
}
validate64.evaluated = {
	props: { "@context": true, type: true, itemListElement: true },
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemStreamEntryObjectList schema.
 */
export const CompiledAuditableItemStreamEntryObjectList: ICompiledValidator = validate66;

function validate66(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/ais/AuditableItemStreamEntryObjectList" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate66.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.itemListElement === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "itemListElement" },
				"must have required property '" + "itemListElement" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 3) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 3 },
						2
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							0
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/ais/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/ais/" },
							0
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				if (len0 > 2) {
					if ("https://schema.3sixty.global/common/" !== data0[2]) {
						const err6 = createError(
							instancePath + "/@context/2",
							"#/properties/%40context/prefixItems/2/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							0
						);
						vErrors = pushError(vErrors, err6);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 3;
				if (!valid2) {
					for (let i0 = 3; i0 < len1; i0++) {
						const _errs6 = errors;
						if (
							!keyword0(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs6 === errors;
					}
				}
			} else {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.type !== undefined) {
			let data5 = data.type;
			if (Array.isArray(data5)) {
				if (data5.length > 2) {
					const err8 = createError(
						instancePath + "/type",
						"#/properties/type/maxItems",
						"maxItems",
						{ limit: 2 },
						8
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				if (data5.length < 2) {
					const err9 = createError(
						instancePath + "/type",
						"#/properties/type/minItems",
						"minItems",
						{ limit: 2 },
						6
					);
					vErrors = pushError(vErrors, err9);
					errors++;
				}
				const len2 = data5.length;
				if (len2 > 0) {
					if ("ItemList" !== data5[0]) {
						const err10 = createError(
							instancePath + "/type/0",
							"#/properties/type/prefixItems/0/const",
							"const",
							{ allowedValue: "ItemList" },
							0
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("AuditableItemStreamEntryObjectList" !== data5[1]) {
						const err11 = createError(
							instancePath + "/type/1",
							"#/properties/type/prefixItems/1/const",
							"const",
							{ allowedValue: "AuditableItemStreamEntryObjectList" },
							0
						);
						vErrors = pushError(vErrors, err11);
						errors++;
					}
				}
				const len3 = data5.length;
				if (!(len3 <= 2)) {
					const err12 = createError(
						instancePath + "/type",
						"#/properties/type/items",
						"items",
						{ limit: 2 },
						8
					);
					vErrors = pushError(vErrors, err12);
					errors++;
				}
			} else {
				const err13 = createError(
					instancePath + "/type",
					"#/properties/type/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.itemListElement !== undefined) {
			let data8 = data.itemListElement;
			if (Array.isArray(data8)) {
				const len4 = data8.length;
				for (let i1 = 0; i1 < len4; i1++) {
					if (
						!keyword1(data8[i1], {
							instancePath: instancePath + "/itemListElement/" + i1,
							parentData: data8,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err14 = createError(
					instancePath + "/itemListElement",
					"#/properties/itemListElement/type",
					"type",
					{ type: "array" },
					3
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
	} else {
		const err15 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err15);
		errors++;
	}
	validate66.errors = vErrors;
	return errors === 0;
}
validate66.evaluated = {
	props: { "@context": true, type: true, itemListElement: true },
	dynamicProps: false,
	dynamicItems: false
};
